<?php
if ( ! defined( 'ABSPATH' ) ) exit;

class Etch_Transfer_Importer {

    /**
     * Main entry point. Accepts both single and multi-export bundles.
     */
    public static function import( $json ) {
        if ( empty( $json ) ) {
            return new WP_Error( 'no_data', 'No JSON data provided.' );
        }

        $data = json_decode( $json, true );

        if ( isset( $data['success'] ) && isset( $data['data'] ) ) {
            $data = $data['data'];
        }

        if ( ! $data || ! isset( $data['etch_export_version'] ) ) {
            return new WP_Error( 'invalid_json', 'Invalid export file. Please use a file generated by Etch Transfer.' );
        }

        // Normalise single export into multi-item shape
        if ( ! isset( $data['etch_export_type'] ) || $data['etch_export_type'] !== 'multi' ) {
            $data = [
                'etch_export_version' => $data['etch_export_version'],
                'etch_export_type'    => 'multi',
                'source_site'         => $data['source_site'] ?? '',
                'item_count'          => 1,
                'items'               => [ $data ],
                'wsf_forms'           => [],
                'etch_styles'         => $data['etch_styles'] ?? [],
            ];
        }

        return self::process_bundle( $data );
    }

    private static function process_bundle( $data ) {
        $imported = [];
        $created  = [];
        $errors   = [];

        // ── WS Forms first — we need the old→new ID map before rewriting page content ──
        $wsf_id_map   = [];   // [ old_source_id => new_dest_id ]
        $wsf_imported = [];
        $wsf_created  = [];

        foreach ( ( $data['wsf_forms'] ?? [] ) as $wsf_entry ) {
            $result = self::import_wsform( $wsf_entry );

            if ( is_wp_error( $result ) ) {
                $errors[] = '"' . ( $wsf_entry['label'] ?? '?' ) . '": ' . $result->get_error_message();
                continue;
            }

            // Map the original source form ID to the new ID on this site
            $old_id = intval( $wsf_entry['source_form_id'] ?? ( $wsf_entry['form_object']['id'] ?? ( $wsf_entry['form_object']->id ?? 0 ) ) );
            if ( $old_id > 0 ) {
                $wsf_id_map[ $old_id ] = $result['id'];
            }

            if ( $result['is_new'] ) {
                $wsf_created[]  = $wsf_entry['label'] ?? '(untitled)';
            } else {
                $wsf_imported[] = $wsf_entry['label'] ?? '(untitled)';
            }
        }

        // ── Standard post items — rewrite WS Form IDs in content after import ──
        foreach ( ( $data['items'] ?? [] ) as $item ) {
            $dest_post = self::resolve_destination( $item );

            if ( is_wp_error( $dest_post ) ) {
                $errors[] = '"' . ( $item['post_title'] ?? '?' ) . '": ' . $dest_post->get_error_message();
                continue;
            }

            // Rewrite WS Form IDs in the post content before writing
            if ( ! empty( $wsf_id_map ) ) {
                $item['post_content'] = self::rewrite_wsf_ids( $item['post_content'], $wsf_id_map );
            }

            $is_new = isset( $dest_post->_is_new ) && $dest_post->_is_new;
            $result = self::write_post( $item, $dest_post->ID );

            if ( is_wp_error( $result ) ) {
                $errors[] = '"' . ( $item['post_title'] ?? '?' ) . '": ' . $result->get_error_message();
                continue;
            }

            if ( $is_new ) {
                $created[] = $item['post_title'] ?? '(untitled)';
            } else {
                $imported[] = $item['post_title'] ?? '(untitled)';
            }
        }

        $styles = self::merge_styles( $data['etch_styles'] ?? [] );

        wp_cache_flush();

        $parts = [];
        if ( ! empty( $imported )     ) $parts[] = count( $imported )     . ' updated';
        if ( ! empty( $created )      ) $parts[] = count( $created )      . ' created';
        if ( ! empty( $wsf_imported ) ) $parts[] = count( $wsf_imported ) . ' WS Forms updated';
        if ( ! empty( $wsf_created )  ) $parts[] = count( $wsf_created )  . ' WS Forms created';
        if ( ! empty( $errors )       ) $parts[] = count( $errors )       . ' failed';

        $msg = 'Import complete from ' . ( $data['source_site'] ?? 'unknown' ) . '. '
             . implode( ', ', $parts ) . '. '
             . $styles['merged'] . ' Etch styles merged.';

        if ( ! empty( $errors ) ) {
            $msg .= ' Errors: ' . implode( '; ', $errors );
        }

        return [
            'message'       => $msg,
            'imported'      => array_merge( $imported, $wsf_imported ),
            'created'       => array_merge( $created,  $wsf_created ),
            'errors'        => $errors,
            'styles_merged' => $styles['merged'],
        ];
    }

    /**
     * Rewrite WS Form IDs in post content.
     *
     * Handles both:
     *   Gutenberg block:  <!-- wp:wsf-block/form-add {"form_id":"3"} -->
     *   Shortcode:        [ws_form id="3"]
     */
    private static function rewrite_wsf_ids( $content, $id_map ) {
        if ( empty( $content ) || empty( $id_map ) ) {
            return $content;
        }

        // Gutenberg block attribute: "form_id":"3" or "form_id": "3"
        $content = preg_replace_callback(
            '/(<!--\s*wp:wsf-block\/form-add\s+)(\{[^}]*"form_id"\s*:\s*")(\d+)(")/i',
            function ( $matches ) use ( $id_map ) {
                $old_id = intval( $matches[3] );
                $new_id = $id_map[ $old_id ] ?? $old_id;
                return $matches[1] . $matches[2] . $new_id . $matches[4];
            },
            $content
        );

        // Shortcode: [ws_form id="3"] or [ws_form id='3']
        $content = preg_replace_callback(
            '/(\[ws_form\b[^\]]*\bid\s*=\s*["\'])(\d+)(["\'][^\]]*\])/i',
            function ( $matches ) use ( $id_map ) {
                $old_id = intval( $matches[2] );
                $new_id = $id_map[ $old_id ] ?? $old_id;
                return $matches[1] . $new_id . $matches[3];
            },
            $content
        );

        return $content;
    }

    /**
     * Import a single WS Form using the exact same sequence as
     * WS_Form_API_Form::api_post_upload_json().
     */
    private static function import_wsform( $wsf_entry ) {
        global $wpdb;

        if ( ! class_exists( 'WS_Form_Form' ) ) {
            return new WP_Error( 'no_wsf', 'WS_Form_Form class not found. Is WS Form active on this site?' );
        }

        $label       = $wsf_entry['label']       ?? '';
        $form_object = $wsf_entry['form_object']  ?? null;

        if ( ! $form_object ) {
            return new WP_Error( 'no_form_data', 'No form_object in export entry.' );
        }

        // JSON-round-trip to stdClass
        if ( is_array( $form_object ) ) {
            $form_object = json_decode( wp_json_encode( $form_object ) );
        }

        $table       = $wpdb->prefix . 'wsf_form';
        $existing_id = $label
            ? $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$table} WHERE label = %s AND NOT (status = 'trash') LIMIT 1", $label ) )
            : null;

        $is_new = false;

        try {
            $ws_form_form = new WS_Form_Form();

            if ( $existing_id ) {
                $ws_form_form->id = (int) $existing_id;
                $form_object->id  = (int) $existing_id;
            } else {
                $ws_form_form->db_create();
                $form_object->id = $ws_form_form->id;
                $is_new          = true;
            }

            $ws_form_form->db_import_reset();
            $form_object->status = 'publish';
            $ws_form_form->db_update_from_object( $form_object, true, true );
            $ws_form_form->db_conditional_repair();
            $ws_form_form->db_action_repair();
            $ws_form_form->db_meta_repair();
            $ws_form_form->db_checksum();
            $ws_form_form->db_style_resolve();

        } catch ( Exception $e ) {
            return new WP_Error( 'wsf_import_failed', $e->getMessage() );
        }

        return [ 'id' => $ws_form_form->id, 'is_new' => $is_new ];
    }

    /**
     * Find existing post by post_type + slug, or create a new one.
     */
    private static function resolve_destination( $item ) {
        $post_type = $item['source_post_type'] ?? 'page';
        $slug      = $item['source_post_name']  ?? '';
        $title     = $item['post_title']         ?? '';

        if ( $slug ) {
            $existing = get_posts([
                'post_type'      => $post_type,
                'name'           => $slug,
                'post_status'    => 'any',
                'posts_per_page' => 1,
            ]);

            if ( empty( $existing ) && $post_type === 'wp_template' && str_contains( $slug, '//' ) ) {
                $short_slug = substr( $slug, strpos( $slug, '//' ) + 2 );
                $existing   = get_posts([
                    'post_type'      => $post_type,
                    'name'           => $short_slug,
                    'post_status'    => 'any',
                    'posts_per_page' => 1,
                ]);
            }

            if ( ! empty( $existing ) ) {
                return $existing[0];
            }
        }

        $new_id = wp_insert_post([
            'post_title'   => $title,
            'post_name'    => $slug,
            'post_type'    => $post_type,
            'post_status'  => $item['post_status'] ?? 'publish',
            'post_content' => '',
        ], true );

        if ( is_wp_error( $new_id ) ) {
            return new WP_Error( 'create_failed', 'Could not create: ' . $new_id->get_error_message() );
        }

        $post          = get_post( $new_id );
        $post->_is_new = true;
        return $post;
    }

    /**
     * Write post content + meta directly via $wpdb, bypassing kses.
     */
    private static function write_post( $item, $dest_post_id ) {
        global $wpdb;

        $updated = $wpdb->update(
            $wpdb->posts,
            [
                'post_content' => $item['post_content'],
                'post_status'  => $item['post_status'],
                'post_title'   => $item['post_title'],
            ],
            [ 'ID' => $dest_post_id ]
        );

        if ( $updated === false ) {
            return new WP_Error( 'db_error', 'DB write failed: ' . $wpdb->last_error );
        }

        $wpdb->delete( $wpdb->postmeta, [ 'post_id' => $dest_post_id ], [ '%d' ] );

        foreach ( ( $item['meta'] ?? [] ) as $row ) {
            $wpdb->insert(
                $wpdb->postmeta,
                [
                    'post_id'    => $dest_post_id,
                    'meta_key'   => $row['meta_key'],
                    'meta_value' => $row['meta_value'],
                ],
                [ '%d', '%s', '%s' ]
            );
        }

        clean_post_cache( $dest_post_id );
        return true;
    }

    private static function merge_styles( $incoming ) {
        if ( empty( $incoming ) || ! is_array( $incoming ) ) {
            return [ 'merged' => 0, 'skipped' => 0 ];
        }

        $dest = get_option( 'etch_styles', [] );
        if ( is_string( $dest ) ) $dest = maybe_unserialize( $dest );
        if ( ! is_array( $dest ) ) $dest = [];

        $merged = $skipped = 0;

        foreach ( $incoming as $id => $style ) {
            if ( isset( $dest[ $id ] ) ) { $skipped++; }
            else { $dest[ $id ] = $style; $merged++; }
        }

        update_option( 'etch_styles', $dest );
        return [ 'merged' => $merged, 'skipped' => $skipped ];
    }
}
